[package]
name = "f_value"
version = "0.1.4"
edition = "2021"
description = "Tool for NISECI and HFBI calc"
license = "GPL-3.0-only"
exclude = [
    ".github/**",
    "assets",
    "templates",
]

[features]
default = ["embed-icon", "rfd-xdg-portal"]
embed-icon = []
rfd-gtk3 = [ "rfd/gtk3" ]
rfd-xdg-portal = [ "rfd/xdg-portal" ]

[build-dependencies]
chrono = "0.4.39"

[dependencies]
chrono = "0.4.44"
dirs = "6.0.0"
esox = "0.1.5"
locale_config = "0.3.0"
miniz_oxide = "0.9.1"
pdf-writer = "0.14.0"
png = "0.18.1"
raylib = { git = "https://github.com/jgabaut/raylib-rs.git", branch = "work/gui_load_style_from_memory", features = [
    "raygui",
] }
rfd = { version = "0.17.2", default-features = false }
