[package]
name = "f_value"
version = "0.1.6"
edition = "2021"
description = "Tool for NISECI and HFBI calc"
license = "GPL-3.0-only"
include = [
    "src/*",
    "LICENSE",
    "assets",
]

[features]
default = ["embed-icon", "lessclone", "rfd-xdg-portal"]
embed-icon = []
lessclone = ["esox/lessclone"]
rfd-gtk3 = ["rfd/gtk3"]
rfd-xdg-portal = ["rfd/xdg-portal"]

[build-dependencies]
chrono = "0.4.45"

[dependencies]
chrono = "0.4.45"
dirs = "6.0.0"
esox = "0.1.6"
locale_config = "0.3.0"
miniz_oxide = "0.9.1"
pdf-writer = "0.15.0"
png = "0.18.1"
raylib = { version = "6.0.0", features = [
    "raygui",
] }
rfd = { version = "0.17.2", default-features = false }
